services:
  frontend:
    image: dhakersg/zaydo-front:latest
    restart: always
    ports:
      - "80:3000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"